{% set name = "taurus_pyqtgraph" %}
{% set version = "0.9.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: aec7e58da154bdc5efc2796cae6bc5a699b8203212d7a26a63cd9065c9c30725

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - click
    - lxml
    - ply
    - pyqtgraph >=0.11
    - python >={{ python_min }}
    - taurus >=4.5.2

test:
  imports:
    - taurus_pyqtgraph
    - taurus_pyqtgraph.examples
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://gitlab.com/taurus-org/taurus_pyqtgraph
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt
  summary: Taurus extension providing pyqtgraph-based widgets
  description: |
    taurus_pyqtgraph is an extension for the Taurus package.
    It adds the taurus.qt.qtgui.tpg submodule which provides pyqtgraph-based
    widgets.
  doc_url: http://taurus-scada.org
  dev_url: https://gitlab.com/taurus-org/taurus_pyqtgraph

extra:
  recipe-maintainers:
    - ovallcorba
    - beenje
    - cpascual
